front:
    resource: "@FrontBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    prefix:   /
